import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import {
  faTimes,
  faCalendar,
  faDollarSign,
  faMoneyBillWave,
  faArrowLeft,
  faPlus,
  faBell,
  faClock,
  faUserCircle,
  faCrown,
  faUserTie,
  faUserGear,
  faEye,
  faQuestionCircle,
  faSignOutAlt,
  faUserPen,
  faGear,
  faUser,
  faLifeRing,
  faCommentDots,
  faDoorClosed,
  faUserSecret,
  faPen,
} from '@fortawesome/free-solid-svg-icons';

export function registerIcons(library: FaIconLibrary): void {
  library.addIcons(
    faTimes,
    faCalendar,
    faDollarSign,
    faMoneyBillWave,
    faArrowLeft,
    faPlus,
    faBell,
    faClock,
    faUserCircle,
    faCrown,
    faUserTie,
    faUserGear,
    faEye,
    faQuestionCircle,
    faSignOutAlt,
    faUserPen,
    faGear,
    faUser,
    faLifeRing,
    faCommentDots,
    faDoorClosed,
    faUserSecret,
    faPen
  );
}
